# fly.toml - Configurazione Fly.io per GameCall Backend

app = "gamecall-api"
primary_region = "ams" # Amsterdam (più vicino all'Italia)

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
