# fly.toml - Configurazione Fly.io per PeerJS Server

app = "gamecall-peerjs"
primary_region = "ams"

[build]

[env]
  PORT = "9000"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
